const rest = require('../../utils/rest.js');
const check = require('starkcore').check;
const Resource = require('../../utils/resource.js').Resource


class Log extends Resource {
    /**
     * 
     * Split Log object
     * 
     * @description Every time a Split entity is updated, a corresponding Split Log
     * is generated for the entity. This log is never generated by the user, 
     * but it can be retrieved to check additional information on the Split.
     * 
     * Attributes:
     * @param id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * @param split [Split]: Split entity to which the log refers to.
     * @param errors [list of strings]: list of errors linked to this Split event.
     * @param type [string]: type of the Split event which triggered the log creation. ex: 'created' or 'updated'
     * @param created [string]: creation datetime for the log. ex: '2020-03-10 10:30:00.000'
     * 
     */
    constructor({ created, type, errors, split, id }) {
        super(id);
        this.split = split;
        this.errors = errors;
        this.type = type;
        this.created = check.datetime(created);
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'SplitLog'};

exports.get = async function (id, {user} = {}) {
    /**
     *
     * Retrieve a specific Split Log
     *
     * @description Receive a single Split Log object previously created by the Stark Bank API by passing its id
     *
     * Parameters (required):
     * @param id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * @param user [Organization/Project object]: Organization or Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * @returns Split Log object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({limit, after, before, types, splitIds, user} = {}) {
    /**
     *
     * Retrieve Split Logs
     *
     * @description Receive a generator of Split Log objects previously created in the Stark Bank API
     *
     * Parameters (optional):
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter for log event types. ex: 'canceled', 'created', 'failed', 'processing', 'success' or 'updated'
     * @param splitIds [list of strings, default null]: list of Split ids to filter logs. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * @returns list of Split Log objects with updated attributes
     *
     */
    let query = {
        limit: limit,
        after: check.date(after),
        before: check.date(before),
        types: types,
        splitIds: splitIds,
    };
    return rest.getList(resource, query, user);
};

exports.page = async function ({ cursor, limit, after, before, types, splitIds, user } = {}) {
    /**
     *
     * Retrieve paged Split Logs
     *
     * @description Receive a generator of Split Log objects previously created in the Stark Bank API
     *
     * Parameters (optional):
     * @param cursor [string, default null]: cursor returned on the previous page function call
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter for log event types. ex: 'canceled', 'created', 'failed', 'processing', 'success' or 'updated'
     * @param splitIds [list of strings, default null]: list of Split ids to filter logs. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * @returns list of Split Log objects with updated attributes and cursor to retrieve the next page of Split Log objects
     *
     */
    let query = {
        cursor: cursor,
        limit: limit,
        after: check.date(after),
        before: check.date(before),
        types: types,
        splitIds: splitIds,
    };
    return rest.getPage(resource, query, user);
}
