const rest = require('../../utils/rest.js');
const Resource = require('../../utils/resource.js').Resource


class Log extends Resource {
    /**
     *
     * Transfer Log object
     *
     * Every time a Transfer entity is modified, a corresponding Transfer Log
     * is generated for the entity. This log is never generated by the
     * user.
     *
     * Attributes:
     * id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * transfer [Transfer]: Transfer entity to which the log refers to.
     * errors [list of strings]: list of errors linked to this BoletoPayment event.
     * type [string]: type of the Transfer event which triggered the log creation. ex: 'processing' or 'success'
     * created [string]: creation datetime for the transfer. ex: '2020-03-10 10:30:00.000'
     *
     */
    constructor({created, type, errors, transfer, id}) {
        super(id);
        this.created = created;
        this.type = type;
        this.errors = errors;
        this.transfer = transfer;
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'TransferLog'};


exports.get = async function (id, {user} = {}) {
    /**
     *
     * Retrieve a specific Transfer Log
     *
     * Receive a single Transfer Log object previously created by the Stark Bank API by passing its id
     *
     * Parameters (required):
     * id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * user [Project object]: Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * Transfer Log object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({limit, after, before, types, transferIds, user} = {}) {
    /**
     *
     * Retrieve Transfer Logs
     *
     * Receive a generator of Transfer Log objects previously created in the Stark Bank API
     *
     * Parameters (optional):
     * limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * before [string, default null] date filter for objects only before specified date. ex: '2020-03-10'
     * types [list of strings, default null]: filter retrieved objects by types. ex: 'success' or 'failed'
     * transferIds [list of strings, default null]: list of Transfer ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * user [Project object, default null]: Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * list of Transfer Log objects with updated attributes
     *
     */
    let query = {limit, after, before, types, transferIds};

    return rest.getList(resource, query, user);
};
