const rest = require('../../utils/rest.js');
const check = require('starkcore').check;
const Resource = require('../../utils/resource.js').Resource


class Log extends Resource {
    /**
     * 
     * SplitReceiver Log object
     * 
     * @description Every time a SplitReceiver entity is updated, a corresponding SplitReceiver Log
     * is generated for the entity. This log is never generated by the user,
     * but it can be retrieved to check additional information on the SplitReceiver.
     * 
     * Attributes:
     * @param id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * @param receiver [SplitReceiver]: SplitReceiver entity to which the log refers to.
     * @param errors [list of strings]: list of errors linked to this SplitReceiver event.
     * @param types [list of strings]: types of the SplitReceiver event which triggered the log creation. ex: 'canceled', 'created', 'failed', 'processing', 'success' or 'updated'
     * @param created [string]: creation datetime for the log. ex: '2020-03-10 10:30:00.000'
     * 
     */
    constructor({ created, types, errors, receiver, id }) {
        super(id);
        this.created = check.datetime(created);
        this.types = types;
        this.errors = errors;
        this.receiver = receiver;
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'SplitReceiverLog'};

exports.get = async function (id, {user} = {}) {
    /**
     * 
     * Retrieve a specific SplitReceiver Log
     * 
     * @description Receive a single SplitReceiver Log object previously created by the Stark Bank API by passing its id
     * 
     * Parameters (required):
     * @param id [string]: object unique id. ex: '5656565656565656'
     * 
     * Parameters (optional):
     * @param user [Organization/Project object]: Organization or Project object. Not necessary if starkbank.user was set before function call
     * 
     * Return:
     * @returns SplitReceiver Log object with updated attributes
     * 
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({limit, after, before, types, receiverIds, user} = {}) {
    /**
     * 
     * Retrieve SplitReceiver Logs
     * 
     * @description Receive a generator of SplitReceiver Log objects previously created in the Stark Bank API
     * 
     * Parameters (optional):
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter for log event types. ex: 'canceled', 'created', 'failed', 'processing', 'success' or 'updated'
     * @param receiverIds [list of strings, default null]: list of SplitReceiver ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkbank.user was set before function call
     * 
     * Return:
     * @returns list of SplitReceiver Log objects with updated attributes
     * 
     */
    let query = {
        limit: limit,
        after: check.date(after),
        before: check.date(before),
        types: types,
        receiverIds: receiverIds,
    };
    return rest.getList(resource, query, user);
};

exports.page = async function ({cursor, limit, after, before, types, receiverIds, user} = {}) {
    /**
     * 
     * Retrieve paged SplitReceiver Logs
     * 
     * @description Receive a list of up to 100 SplitReceiver Log objects previously created in the Stark Bank API and the cursor to the next page.
     * Use this function instead of query if you want to manually page your requests.
     * 
     * Parameters (optional):
     * @param cursor [string, default null]: cursor returned on the previous page function call
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter for log event types. ex: 'canceled', 'created', 'failed', 'processing', 'success' or 'updated'
     * @param receiverIds [list of strings, default null]: list of SplitReceiver ids to filter logs. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkbank.user was set before function call
     * 
     * Return:
     * @returns list of SplitReceiver Log objects with updated attributes and cursor to retrieve the next page of SplitReceiver Log objects
     * 
     */
    let query = {
        cursor: cursor,
        limit: limit,
        after: check.date(after),
        before: check.date(before),
        types: types,
        receiverIds: receiverIds,
    };
    return rest.getPage(resource, query, user);
};
