const rest = require('../../utils/rest.js');


class BoletoPaymentLog {
    /**
     *
     * BoletoPaymentLog object
     *
     * Every time a BoletoPayment entity is modified, a corresponding BoletoPaymentLog
     * is generated for the entity. This log is never generated by the
     * user, but it can be retrieved to check additional information
     * on the BoletoPayment.
     *
     * Attributes:
     * id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * payment [BoletoPayment]: BoletoPayment entity to which the log refers to.
     * errors [list of strings]: list of errors linked to this BoletoPayment event.
     * type [string]: type of the BoletoPayment event which triggered the log creation. ex: 'registered' or 'paid'
     * created [string]: creation datetime for the payment. ex: '2020-03-10 10:30:00.000'
     *
     */
    constructor({created, type, errors, payment, id}) {
        this.created = created;
        this.type = type;
        this.errors = errors;
        this.payment = payment;
        this.id = id;
    }
}

exports.BoletoPaymentLog = BoletoPaymentLog;
let resource = exports.BoletoPaymentLog;


exports.get = async function (id, user = null) {
    /**
     *
     * Retrieve a specific BoletoPaymentLog
     *
     * Receive a single BoletoPaymentLog object previously created by the Stark Bank API by passing its id
     *
     * Parameters (required):
     * id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * user [Project object]: Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * BoletoPaymentLog object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({limit = null, status = null, tags = null, ids = null, after = null, before = null}, user = null) {
    /**
     *
     * Retrieve BoletoPaymentLogs
     *
     * Receive a generator of BoletoPaymentLog objects previously created in the Stark Bank API
     *
     * Parameters (optional):
     * limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
     * payment_ids [list of strings, default None]: list of BoletoPayment ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * types [list of strings, default None]: filter retrieved objects by event types. ex: 'paid' or 'registered'
     * user [Project object, default None]: Project object. Not necessary if starkbank.user was set before function call
     *
     * Return:
     * list of BoletoPaymentLog objects with updated attributes
     *
     */
    let query = {
        limit: limit,
        status: status,
        tags: tags,
        ids: ids,
        after: after,
        before: before,
    };
    return rest.getList(resource, query, user);
};
