let corporateCard = require('./corporateCard.js');
exports.CorporateCard = corporateCard.CorporateCard;
exports.create = corporateCard.create;
exports.query = corporateCard.query;
exports.page = corporateCard.page;
exports.get = corporateCard.get;
exports.update = corporateCard.update;
exports.cancel = corporateCard.cancel;
exports.log = require('./log');
